# Creating DataFrames

Many ways to do it!

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.random.random(size=(5, 3))
print(data)

# Common 2D array and columns method
df = pd.DataFrame(data=data, columns=["A", "B", "C"])
df

[[0.24874164 0.46269324 0.57735715]
 [0.9933599  0.81478057 0.29990417]
 [0.50054054 0.51743019 0.87618937]
 [0.05915842 0.79047784 0.09129382]
 [0.79421887 0.62386316 0.78006764]]


A         B         C
0  0.248742  0.462693  0.577357
1  0.993360  0.814781  0.299904
2  0.500541  0.517430  0.876189
3  0.059158  0.790478  0.091294
4  0.794219  0.623863  0.780068

In [6]:
# A dictionary of columns
df = pd.DataFrame(data={"A": [1, 2, 3], "B": ["Sam", "Alex", "John"]})
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [9]:
# Or a list of rows (ie tuples) with a dtype
dtype = [("A", np.int), ("B", (np.str, 20))]
data = np.array([(1, "Sam"), (2, "Alex"), (3, "John")], dtype=dtype)
df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [10]:
# Or the dictionary based version of list of rows
data = [{"A": 1, "B": "Sam"}, {"A": 2, "B": "Alex"}, {"A": 3, "B": "John"}]
df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John